### ISSUE TITLE
Initial scroll position

### ISSUE THREAD

**Issue by buu700** [dinony/od-virtualscroll#17]
What is the intended initial scroll position intended to be? In my application, it seems to randomly alternate between starting at the top of the list and starting at the bottom of the list.

Could this setting be configurable? I have one use case where I would prefer to start at the top (contacts list) and another where I would want to start at the bottom (message history).

**Comment by dinony** [comment]
What do you mean by initial scroll pos? Initial scroll position should be at top, if not scrolled yet. 
On a sidenote: You can send [commands](https://github.com/dinony/od-virtualscroll#iusercmd) to focus a certain row, if you want.

**Comment by buu700** [comment]
Thanks for the clarification! I had some cases where it wasn't at the top, so if that wasn't by design then it's possible that it was a browser feature to remember where I'd scrolled previously, in which case I may consider using those commands.

Closing this for now until I see something that definitely seems to be a bug.
