### ISSUE TITLE
How can I integrate a search/filter functionality?

### ISSUE THREAD

**Issue by okon3** [dinony/od-virtualscroll#20]
I have a huge list of items displayed using the od-virtualscroll and it works great, the only thing i'm missing is implementing a search functionality.
I tried supplying a new Observable with the filtered values to the od-virtualscroll component but it's not working.

Should i combine the observable of values with a stream of filter values (using .combineLatest) and filter using .filter to feed the component `vsData`?

**Comment by dinony** [comment]
Hi, do not supply a new observable. Just emit the new filtered array.
Yes, using combineLatest on both observables + filter to create the observable of filtered data is the way to go.

**Comment by dinony** [comment]
Ok, feel free to open up again, if there are issues.

**Comment by okon3** [comment]
I'm having issues implementing this. It seems like there's a bug somewhere in how the updates to the observables are handled.

Essentialy I have an `<input>` and a list of values being displayed. I need to filter the list upon entering something in the input value.

I have my observables setup like this:
```
//empty initial state
private INIT_STATE = [];
//stream of all the values to be displayed. Initializated with an empty array and gets updated after an api request ends
private filterValuesSource = new BehaviorSubject(this.INIT_STATE);
//Stream of search values
private searchValues = new BehaviorSubject('');
//od-virtualscoll options
$options: Observable<IVirtualScrollOptions> = Observable.of({ itemHeight: 35, numAdditionalRows: 1, numLimitColumns: 1 });

//this is the observable fed to od-virtualscroll
$filteredArray = this.filterValuesSource
	.asObservable()
	.combineLatest(this.searchValues, (values, filter) =>
		({ values, filter })
	).map(el => {
		let returnArray = [];
		if (el.filter !== null && el.filter !== undefined && el.filter !== '') {
			returnArray =  el.values.filter(value => {
				return value.value.toLowerCase().indexOf(el.filter.toLowerCase()) !== -1;
			});
		} else {
			returnArray = el.values;
		}
		console.log(returnArray); //HERE MY ARRAY IS CORRECLY FILTERED
		return returnArray;
	});
```

this is the code that updates the values in the array (they come as an `@Input` to the component)

```
ngOnChanges(changes: SimpleChanges): void {
	if (changes._filterValues && !changes._filterValues.firstChange) {
		const arrayOfValues = new Array<FiltersPageFiltersValue>();
		for (let i = 0; i < this._filterValues.values.length; i++) {
			arrayOfValues.push(this._filterValues.values[i].value);
		}

		this.filterValuesSource.next(arrayOfValues);
	}
}
```

and this is the keyup handler on my `<input>` element

```
onSearch(event) {
	const searchWord = event.target.value;
	this.searchValues.next(searchWord);
}
```

The list is correctly displayed empty at the beginning, then updated when I push the values in the observable (in the `ngOnChanges`).
The problem occurs when I type something into the `input`. The list is correctly filtered in the .map after the .combinelatest but then the wrong items are displayed in the od-virtualscroll.

To clarify the problem i have a list with different years (from 2000 to 2017). If i type '7' in the input element my filter function logs ['2017', '2007'] to the console but 2017 and 2016 are displayed in the component (which are the first 2 elements of the original array).

**Comment by okon3** [comment]
The problem seems to be that the list is not entirely re-drawn.
If i type in the search box '7' the resulting list is incorrectly displayed as 2017, 2016 I then type 'a' so the resulting list is empty, I then type '7' again, now the list shows 2017, 2007 correctly.

**Comment by dinony** [comment]
Sorry, didn't read in detail but it sounds like you have to implement the `vsEqualsFunc`. The default `vsEqualsFunc` just compares the indices and if they are the same, the cell is not updated. Since the model for a cell could be arbitrary you can provide a custom method for [equality checking](https://github.com/dinony/od-virtualscroll/#inputs).
Ok, maybe this helps already. If not I will get to this issue in more detail soon&#8482;.

**Comment by okon3** [comment]
~~That definetly helped, it solved my problem.~~
Maybe you should provide an example with a search box implemented.
Also i think the documentation isn't perfectly clear on when you should define your own `vsEqualsFunc` function.

Thanks!

**EDIT:**

No wait, I messed up something, I didn's save properly so I was still seeing my workaround.
As soon as i passed the equalFunc i wrote it stopped working again... (as of now i'm triggering a search that produces no results before triggering the actual search)

```
equalFunc = (a, b) => {
	console.log(a);
	console.log(b);
	return a.value === b.value;
}
```

What's the input to the `vsEqualsFunc` ? both `a` and `b` are only indexes and not objects from my array. I'm confused, how should i use this? If i print a and b when triggering a search that should produce 2 results i get:

```
0
0
1
1
```

Thanks again

**Comment by dinony** [comment]
Yep, you're right. It definitely needs better documentation and also I need to rethink the equality checking.
There is an [example](https://dinony.github.io/od-vsdynamic/) with a search box, it's another scenario, but I hope it helps for now.
Yes, the `vsEqualsFunc` receives two indices, and with the current array you should be able to implement the equality checking.

**Comment by okon3** [comment]
I'm looking at the examples, are those supposed to be the indexes of the element before and after the update to the observable?

**Comment by dinony** [comment]
Ah yes, you also need the previous array. Check whether the data at `prevIndex` in the previous array is equal to `curIndex` in the current array.

**Comment by okon3** [comment]
NOW i got it!
Essentially the parameters to the function will always be the same indexes, i need to manually check them against the previous and current array. That wasn't really clear :D

**Comment by dinony** [comment]
Ok good :) Yeah sry, I need to work on the docs and also rethink the equals func.
But I'm quite sure that the indices could be different, it should not always be the same (e.g. when resize happens?)

**Comment by okon3** [comment]
Seems like the equalfunc is used also when i'm just scrolling the view... and that makes me think..
Should't be there 2 different functions? The same function used to check if value at position `i` is the same in the current and previous array is also used when scrolling which is based only on the current array..

**Comment by dinony** [comment]
Yep, it needs more thinking, I'd need to look into the source again - it's on the radar.
If your current issue is solved for now, I'd like to close the issue.

**Comment by okon3** [comment]
In this instance i solved it returning false in the equalsfunc so that everything gets redrawn from scratch.
I dont have performance issues for now and i'm happy with it.
Thanks
