### ISSUE TITLE
Incorrect positioning

### ISSUE THREAD

**Issue by buu700** [dinony/od-virtualscroll#21]
I'm not sure if my code is doing something wrong, or maybe #16 caused a regression, but occasionally I'll have items get incorrectly positioned. My message "10" shows up in the DOM, but with an incorrect `translateY` value that causes it to appear off-screen. Resizing the window and/or adding more list items sometimes fixes this.

re: #16, at one point I was able to reproduce something similar with the current master branch and static heights, such that there would be visibly overlapping items, so I think it probably isn't the root cause.

<img width="1227" alt="screen shot 2017-12-05 at 7 50 05 pm" src="https://user-images.githubusercontent.com/415435/33638754-ad3f56f4-d9f5-11e7-8af4-5c628840ca21.png">

**Comment by dinony** [comment]
Ok, I will get to your #16 soon. If it's an issue on the master branch, a minimal code reproduction would be awesome.
