### ISSUE TITLE
Async data

### ISSUE THREAD

**Issue by buu700** [dinony/od-virtualscroll#22]
I have a case where the component within the virtual scroll `ng-template` needs to fetch some remote data before it will display anything. Specifically, `ngOnInit` will fetch the data if it isn't already cached locally, and the top-level element of the component has something to the effect of `*ngIf='valueObservable | async; let value'`.

However, when adding a lot of items at once and immediately scrolling to them, I'll see many gaps in the list that don't get filled until I scroll away and scroll back. Is there some kind of caching of DOM elements or something that could be causing this, or is it more likely a mistake on my end?

**Comment by dinony** [comment]
Sry, for responding similar to your other issues, but I really need to see a code example. It would be great if you could separate this issue from your use case and provide a minimal example.

**Comment by buu700** [comment]
Got it, I'll try to reproduce all these in isolated examples without #16 in the mix and get back to you.
