### ISSUE TITLE
Incorrect height

### ISSUE THREAD

**Issue by buu700** [dinony/od-virtualscroll#23]
In one place where I'm using this, the list starts out only showing items in the top ~60% of the view even though much more space is available and scrollable:

<img width="1340" alt="screen shot 2017-12-05 at 8 02 29 pm" src="https://user-images.githubusercontent.com/415435/33642580-883681da-da08-11e7-962e-8eba75d879fd.png">

However, this immediately corrects itself when I resize the window once. Also, when displaying elements larger than the ones in the screenshot (using #16), it fills up a little bit more of the available space:

<img width="1340" alt="screen shot 2017-12-05 at 10 07 51 pm" src="https://user-images.githubusercontent.com/415435/33642640-cf0222c2-da08-11e7-8ab7-3f84eb3ee25f.png">

**Comment by dinony** [comment]
Hmm, code would be great. I can't tell from the screenshots and it would be really nice if it's isolated from #16, which I even haven't reviewed yet :) (but I will!)

**Comment by dinony** [comment]
I will close your issues with the label `needs more info` for now. Let me know if you have an isolated repro example.
