### ISSUE TITLE
Cannot get anything to display

### ISSUE THREAD

**Issue by ericcancil** [dinony/od-virtualscroll#24]
Kind of at a loss at this point

I've tried getting the absolute simplest working implementation of this, and nothing ever shows.  Would really appreciate some feedback

View

```
<od-virtualscroll [vsData]="data" [vsOptions]="options">
      <ng-template let-item let-row="row" let-column="column">
        <span>Row: {{row}}</span><br>
        <span>Column: {{column}}</span>
        {{item}}
      </ng-template>
    </od-virtualscroll>
```

TS

```
constructor(private element : ElementRef, public authModel:AuthModel, private services:Services) {
      let dateSearch = new DateSearchDescriptor()
      dateSearch.zipcode = 11211
      this.data = this.services.getDates(dateSearch)

      this.options = Observable.of({itemWidth: 202, itemHeight: 202, numAdditionalRows: 1})
  }
```

**Comment by dinony** [comment]
Hi, could you provide more detail what `this.services.getDates(dateSearch)` returns?
Other than that, it could also be possible that the styling of the cells is not correct. 
Maybe you could compare your component with [this](https://github.com/dinony/od-vsstatic/tree/master/src/scroll).

**Comment by ericcancil** [comment]
@dinony Thanks for the reply.  It returns an observable with a collection of custom objects

**Comment by dinony** [comment]
Ok, I just want to make sure that `this.services.getDates(dateSearch)` return type is `Observable<any[]>`.
Could you provide some info on the styling?
