### ISSUE TITLE
ios/android No Items are rendering.

### ISSUE THREAD

**Issue by Ramachandrajoshi** [dinony/od-virtualscroll#26]
row items are not rendering in mobile devices. used in ionic 3 project. shows only numAdditionalRows items. not the calculated ones.
even on chrome browser debugging mode if we make the mobile screen mode and reload the page. list is loading only how many items we mentioned as numAdditionalRows.

**Comment by dinony** [comment]
Hi, hm that's strange. Any chance to see reproduction code?

**Comment by Ramachandrajoshi** [comment]
hi,
Im able to solve it by setting the height for od-virtualscroll tag.
here i reproduced by changing CSS in od-vslist repo.
![screenshot from 2018-02-03 09-44-59](https://user-images.githubusercontent.com/14068607/35762957-8ac755d0-08c7-11e8-989c-1be104afe755.png)

here it was showing only items which are mentioned as numAdditionalRows.

**Comment by dinony** [comment]
I think you forgot the link. I just see the image?

**Comment by Ramachandrajoshi** [comment]
There is not much change to do in your demo project. Just to comment those 2 height values in css will reporduce the issue. So i dident posted the whole project.

**Comment by Ramachandrajoshi** [comment]
And it makes sense to give a fixed height either from programetically or manuvally to calculate the renderable cells in a scroll. So I think its beter to mention in the README.MD with must give height to the element.
I have used angular @ViewChild() option to get the parent element height and setting it to the od-virtualscroll via [ngStyle] attribute. It may help other who face the issue when making their website responsive.

I used this in my ionic 3 project. Its pretty good. Thank you for making it.

**Comment by Ramachandrajoshi** [comment]
And it makes sense to give a fixed height either from programetically or manuvally to calculate the renderable cells in a scroll. So I think its beter to mention in the README.MD with must give height to the element.
I have used angular @ViewChild() option to get the parent element height and setting it to the od-virtualscroll via [ngStyle] attribute. It may help other who face the issue when making their website responsive.

I used this in my ionic 3 project. Its pretty good. Thank you for making it.

**Comment by dinony** [comment]
The client rect of the scroll component is given by [`rect$`](https://github.com/dinony/od-virtualscroll/blob/master/src/virtualScroll.component.ts#L112). But I suspect that `getBoundingClientRect()` is not available when used with ionic. If that's the case, there needs to be a new option, where the user either specifies the client rect observable himself or the current fallback is used. 
I haven't used ionic yet, but I will try it out - thanks for reporting the issue!

**Comment by Ramachandrajoshi** [comment]
Its not specific to ionic. In this issue reproduce project is one your demos. It was related to mobile specific user-agent or the mobile browser engin rendering problem. So no need to be inspect it by using on ionic project i think.

**Comment by dinony** [comment]
Ok, what browser is it?

**Comment by Ramachandrajoshi** [comment]
Google chrom is enough to inspect. But try by making it mobile resolution in inspector tab.

**Comment by Ramachandrajoshi** [comment]
Ionic uses mobile webview which is kinda chrome like browser with less controlls.

**Comment by dinony** [comment]
<img width="1240" alt="screen shot 2018-02-06 at 20 58 32" src="https://user-images.githubusercontent.com/2547965/35881268-9682f292-0b80-11e8-8e57-5243d2a53c0b.png">
Chrome works as expected. I still don't get what your issue is, other than that I suspect it's something related to ionic.
Would be super cool if you could provide a minimal ionic wrapper example proving the issue. Otherwise I will try to setup a ionic example.

**Comment by pjc2007** [comment]
Just watching this thread (as may want to use in Ionic in the future) .
Ionic have a minimal template on plunkr.

May help in a minimal example?

http://plnkr.co/edit/z0DzVL?p=preview

**Comment by Ramachandrajoshi** [comment]
please take a look at this repo for issue.

https://github.com/Ramachandrajoshi/od-virtualscroll_bug_reproduce

Note: re-sizing the window will shows the items correctly. but once refresh the browser it wont give all the items again.

Another mention: ```equal``` function is Important to render the updates in observable. by default if observable array is updated it wont reflect the changes until go out of the view port and comes again.
fix: implementing the ```equal``` function and ```return false```. conditional return is best for performance perspective.

please give more detailed documentation about this ```equal``` function.

**Comment by dinony** [comment]
@Ramachandrajoshi: The problem is that you commented out the [height](https://github.com/Ramachandrajoshi/od-virtualscroll_bug_reproduce/blob/master/src/app.component.css#L19) property on the wrapper div. What's your use case on that?
You need to define a height on the scroll container, otherwise the container will grow.

Regarding `vsEqualsFunc`: I thinking about other solutions for this. See [issue](https://github.com/dinony/od-virtualscroll/issues/20) here. But I will try to improve the current docs, thanks for the feedback!

@pjc2007: yeah thanks, will have a look at it.

**Comment by Ramachandrajoshi** [comment]
Yaa. Giving the height is important to calculate number of items should be drawn on the viewport. But on responcive design we cant always give fixed height for a view. But as i said earlier it was fixed by angular @viewChild() and getting the height in programettically and setting it to scrollview.

So please close the issue.

Regarding ```vsEqualsFunc```: if you able to return prev object and current object insted of the index number it would be good to compare those 2 and will return the status based on that.

**Comment by dinony** [comment]
Ok. Yep, was also thinking in this direction with `vsEqualsFunc`.
