### ISSUE TITLE
FocusRowIndex

### ISSUE THREAD

**Issue by gabrielste1n** [dinony/od-virtualscroll#28]
I am trying to use FocusRowCmd to naviagte to a specific row (in this case i have hard-coded it to row 20)

![scrollcomponenet](https://user-images.githubusercontent.com/11309189/41606246-872fd514-73e3-11e8-95d7-7058b73cd1a3.PNG)

I couldn't find an implementation of an of the userCmd$ options, the above code snippet does not have the desired affect, it currently only displays the list, but i am expecting it to focus on row 20, i have also tried the same with SetScrollTopCmd and it does not work either. Could you please shed light as to what i am doing wrong? The HTML is below, along with the current output.

![html](https://user-images.githubusercontent.com/11309189/41606486-12eb0d80-73e4-11e8-9150-667f355309b3.PNG)

and the output

![scroll](https://user-images.githubusercontent.com/11309189/41606544-3122cf72-73e4-11e8-9c50-a3dcde808ab0.PNG)

I am expecting something like

![row20](https://user-images.githubusercontent.com/11309189/41606639-705023d4-73e4-11e8-9498-63a93d99d20c.PNG)

i am aware the "names" are the same, that is because my list that i am using is made of 5 entries duplicated around 60 times

thanks

**Comment by dinony** [comment]
Just quick guess: could you try to add a little bit of a [delay](https://github.com/dinony/od-virtualscroll#iusercmd)?

Edit: 
Fyi: The delay is needed, because 1 initial render pass needs to happen to initialize the container div height, before focus commands can work.

**Comment by gabrielste1n** [comment]
Thanks for replying so quickly, that is definitely the problem, but could you tell me where to import delay from?

 i  have tried:

import { delay } from 'rxjs/add/operator';

and

import { delay } from 'rxjs/operators';

I'm assuming these are wrong?

Thanks again

**Comment by dinony** [comment]
Np! Since `v1.1.x` uses RxJS6 it should be

```javascript
import {delay} from 'rxjs/operators'
```

If you're using `v1.0.x` then it should be (RxJS5 style)

```javascript
import 'rxjs/add/operator/delay';
```

Edit: In your screenshot you're using RxJS6, so the first import should work?
Edit2: Ah wait, it should be 

```of(...).pipe(delay(2000))```

I've corrected the readme.

**Comment by gabrielste1n** [comment]
I have no clue why it is not working 

![capture](https://user-images.githubusercontent.com/11309189/41610132-b31d2290-73ec-11e8-9816-b6a00d8111af.PNG)

**Comment by dinony** [comment]
Yep, corrected the readme. It should be:

```javascript
of(new FocusRowCmd(20)).pipe(delay(2000))
```

On a sidenote: `delay(0)` works too, because the `async` scheduler is used and the command enters after the initial render.

**Comment by gabrielste1n** [comment]
You are too good for this world! Thank you sir!
