### ISSUE TITLE
[bug report] AOT support broken

### ISSUE THREAD

**Issue by buu700** [dinony/od-virtualscroll#3]
Just importing `VirtualScrollModule` causes my otherwise AOT-compatible project to fail compilation with the error `ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /node_modules/@angular/core/core.d.ts`.

It's possible that this is specific to only Angular 4.1 and/or TypeScript 2.3, as I haven't tested with any other versions of either of them.

**Comment by dinony** [comment]
What is your setup for AoT compilation? Are you using any tools or just ngc?

**Comment by buu700** [comment]
Currently @ngtools/webpack, but if it's helpful I can test using ngc directly as well.

**Comment by dinony** [comment]
Sure, that would be great. For the demos I've provided I used ngc directly. I have to test the cli yet.

**Comment by dinony** [comment]
Hey, I've tested Angular CLI and had no problems when using the `--aot` option. Are you using @ngtools/webpack in a custom webpack setup?

To make sure: Just `importing` the module already causes the compiler error? So there is no additional application code added to consume the component yet?

**Comment by buu700** [comment]
Hmm, well this is strange. It works fine with `ngc`, but building with @ngtools/webpack (custom webpack setup, no Angular CLI) consistently causes the failure above. This is probably just something in our configuration that we need to fix, so I'll go ahead and close this ticket for now.

And yep, just importing; this is the full diff of the change that causes the build failure:

<img width="601" alt="screen shot 2017-04-29 at 5 28 08 pm" src="https://cloud.githubusercontent.com/assets/415435/25559178/42d160ee-2d04-11e7-8d70-25af14646e07.png">

**Comment by buu700** [comment]
Okay yeah, this turned out to just be an edge case issue with our build script; not exactly sure of the cause or why this module happened to trigger it, but in any case AOT is working now after fixing it.

**Comment by dinony** [comment]
Oh, happy that it worked out! Unfortunately, ngc is documented sparsely and the compiler error messages are very cryptic currently. So, feel free to post an update, if you find out anything meaningful what was causing the problem in your custom build - I'd imagine that others may end up having the same problem.
