### ISSUE TITLE
[bug report] Resizing broken

### ISSUE THREAD

**Issue by buu700** [dinony/od-virtualscroll#4]
I don't have an isolated test case right now, but in my project if the list gets resized for any reason (resizing the JS console, new element appearing underneath it, etc.), it locks the current viewport in place and virtual scrolling no longer works.

It's possible that this is related to Flexbox/[flex-layout](https://github.com/angular/flex-layout). This is the relevant section of the template where it's being triggered:

```
<div fxFlex fxLayout='row'>
	<od-virtualscroll [vsData]='vsMessages' [vsOptions]='vsOptions'>
		<ng-template let-item>
			<cyph-chat-message
				[message]='item'
				[mobile]='mobile'
				[unconfirmedMessages]='unconfirmedMessages'
			></cyph-chat-message>
		</ng-template>
	</od-virtualscroll>
</div>
```

Also potentially relevant: od-virtualscroll doesn't seem to quite work with flex-layout directives (in particular `fxFlex` and `fxFlexFill`), so as a workaround I'm using the following CSS: `od-virtualscroll, od-virtualrow { width: 100%; }`.

**Comment by dinony** [comment]
An isolated plunker would be very helpful, but I will also look into the flex-layout lib.

**Comment by dinony** [comment]
I've checked the flex-layout lib and used the static API to recreate the static example - there were no problems for me. 

Could you check whether the overflow is handled correctly on the containers? If `.od-scroll-container`, which gets the actual height, is somehow not wrapped by a container with `overflow: scroll` (default) or `overflow: hidden` defining the viewport, the `viewport height === total height` and that would bypass virtualization.

**Comment by buu700** [comment]
Thanks for looking into this! Oddly, I can't reproduce the problem anymore, despite that I haven't touched the branch where I'd implemented this since my original reddit comment.

As far as overflow, not that it matters if this actually isn't a problem, but the `od-virtualscroll` element is descended from a `div` with `overflow: scroll` and the ancestors in between have the default value of `overflow: visible`.
