### ISSUE TITLE
Question: How do I go to an item?

### ISSUE THREAD

**Issue by manju-reddys** [dinony/od-virtualscroll#7]
I don't see a way to go directly a give item (index) in the list?

**Comment by dinony** [comment]
Hi manju, that's a good idea. Currently, you can specify  a `Observable<SetScrollTopCmd>`, where the `SetScrollTopCmd` specifies a scrollTop position.

But it's a good idea to also allow navigating to a certain row position - maybe I'll have some time to look at this in the next days.

**Comment by dinony** [comment]
This is supported in v1.x via the `vsUserCmd` input variable.
